server:
  port: 11000

spring:
  application:
    name: simply

  datasource:
    url: jdbc:postgresql://localhost:5432/simply
    schema: main
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: simplyPool
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
      default-schema: main

# http://localhost:11000/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config
springdoc:
  version: 1.0.0

logging:
  charset:
    console: UTF-8